version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: jangkriknet_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: jangkriknet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jangkriknet_app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgrespassword@postgres:5432/jangkriknet?schema=public"
      JWT_SECRET: "jangkriknet-production-secure-jwt-key-2026"
      APP_URL: "http://localhost:3000"
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/app/public/uploads

volumes:
  postgres_data:
  uploads_data:
